services:
  - type: web
    name: final-rvm-schedulerfaridabad
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: supabase